In [1]:
from sklearn.linear_model import LogisticRegression 
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.datasets import load_digits
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [3]:
# Logistic Regression

lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9462962962962963

In [4]:
# SVM
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9851851851851852

In [5]:
# Random Forest

rf = RandomForestClassifier(n_estimators=50)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9648148148148148

**KFold cross validation**

**Basic example**

In [6]:
from sklearn.model_selection import KFold
kf = KFold()
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [7]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[2 3 4 5 6 7 8] [0 1]
[0 1 4 5 6 7 8] [2 3]
[0 1 2 3 6 7 8] [4 5]
[0 1 2 3 4 5 8] [6 7]
[0 1 2 3 4 5 6 7] [8]


**Use KFold for our digits example**

In [8]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [9]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [10]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [11]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [12]:
scores_rf

[0.9298831385642737, 0.9515859766277128, 0.9215358931552587]

**cross_val_score function**

In [13]:
from sklearn.model_selection import cross_val_score

In [14]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data,digits.target ,cv = 4)

array([0.93777778, 0.91091314, 0.95768374, 0.90423163])

In [15]:
cross_val_score(SVC(),digits.data,digits.target ,cv = 3)


array([0.96494157, 0.97996661, 0.96494157])

In [16]:
cross_val_score(RandomForestClassifier(n_estimators = 50),digits.data,digits.target ,cv = 3)


array([0.94490818, 0.93989983, 0.92487479])

**Exercise**

Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,

* Logistic Regression
* SVM
* Decision Tree
* Random Forest

In [17]:
from sklearn.datasets import load_iris
iris = load_iris()

In [18]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [19]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),iris.data,iris.target ,  cv =3).mean()

0.9533333333333333

In [20]:
cross_val_score( SVC(),iris.data,iris.target ,  cv =3).mean()

0.96

In [21]:
cross_val_score(DecisionTreeClassifier(),iris.data,iris.target , cv =3).mean()


0.9666666666666667

In [22]:
cross_val_score(RandomForestClassifier(n_estimators=20),iris.data,iris.target, cv =3).mean()


0.96

In [23]:
def best_model(iris):
    
    lg_score = cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),iris.data,iris.target ,  cv =3).mean()
    svc_score=cross_val_score( SVC(),iris.data,iris.target , cv =3).mean()
    tree_score=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target , cv =3).mean()
    rf_score = cross_val_score(RandomForestClassifier(n_estimators=20),iris.data,iris.target, cv =3).mean()

    lt = [lg_score,svc_score,tree_score,rf_score]
    
    return max(lt)
    
    
best_model(iris)

0.9666666666666667

In [24]:
def best_model(iris):
    models = {
        "Logistic Regression": cross_val_score(LogisticRegression(solver='liblinear', multi_class='ovr'), iris.data, iris.target, cv=3).mean(),
        "SVC": cross_val_score(SVC(), iris.data, iris.target, cv=3).mean(),
        "Decision Tree": cross_val_score(DecisionTreeClassifier(), iris.data, iris.target, cv=3).mean(),
        "Random Forest": cross_val_score(RandomForestClassifier(n_estimators=20), iris.data, iris.target, cv=3).mean()
    }

    best_model_name = max(models, key=models.get)  # Get model with highest score
    return best_model_name, models[best_model_name]

# Call function
print("Best model:", best_model(iris))

Best model: ('SVC', 0.96)
