In [1]:
from sklearn.linear_model import LogisticRegression 
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.datasets import load_digits
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [3]:
# Logistic Regression

lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9518518518518518

In [4]:
# SVM
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9833333333333333

In [5]:
# Random Forest

rf = RandomForestClassifier(n_estimators=50)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9666666666666667

**KFold cross validation**

**Basic example**

In [6]:
from sklearn.model_selection import KFold
kf = KFold()
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [7]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[2 3 4 5 6 7 8] [0 1]
[0 1 4 5 6 7 8] [2 3]
[0 1 2 3 6 7 8] [4 5]
[0 1 2 3 4 5 8] [6 7]
[0 1 2 3 4 5 6 7] [8]


**Use KFold for our digits example**

In [8]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [9]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [10]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [11]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [12]:
scores_rf

[0.9298831385642737, 0.9582637729549248, 0.9265442404006677]

**cross_val_score function**

In [13]:
from sklearn.model_selection import cross_val_score

In [14]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data,digits.target ,cv = 4)

array([0.93777778, 0.91091314, 0.95768374, 0.90423163])

In [15]:
cross_val_score(SVC(),digits.data,digits.target ,cv = 3)


array([0.96494157, 0.97996661, 0.96494157])

In [16]:
cross_val_score(RandomForestClassifier(n_estimators = 50),digits.data,digits.target ,cv = 3)


array([0.93656093, 0.94657763, 0.92654424])

**Exercise**

Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,

* Logistic Regression
* SVM
* Decision Tree
* Random Forest