In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/hiring/hiring.csv
/kaggle/input/realstate-data/real_estate_data.csv


In [2]:
import matplotlib.pyplot as plt

In [3]:
from sklearn import linear_model

In [4]:
import math

In [5]:
df = pd.read_csv("/kaggle/input/realstate-data/real_estate_data.csv")

In [6]:
df.head(5)

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()


Area (sq ft)  Bedrooms  Price (in lakhs)  Age (years)
0          2678       3.0               115         19.0
1          1326       3.0               116          0.0
2           872       2.0                58          8.0
3           609       4.0               205          NaN
4          2560       2.0               189         10.0

In [7]:
median_bedrooms = math.floor(df.Bedrooms.median())

In [8]:
df.Bedrooms.fillna(median_bedrooms).head()

0    3.0
1    3.0
2    2.0
3    4.0
4    2.0
Name: Bedrooms, dtype: float64

In [9]:
df.Bedrooms = df.Bedrooms.fillna(median_bedrooms)
df.head()

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()


Area (sq ft)  Bedrooms  Price (in lakhs)  Age (years)
0          2678       3.0               115         19.0
1          1326       3.0               116          0.0
2           872       2.0                58          8.0
3           609       4.0               205          NaN
4          2560       2.0               189         10.0

In [10]:
mean_age = math.floor(df["Age (years)"].mean())
df["Age (years)"] = df["Age (years)"].fillna(mean_age)


In [11]:
df.head(8)

Area (sq ft)  Bedrooms  Price (in lakhs)  Age (years)
0          2678       3.0               115         19.0
1          1326       3.0               116          0.0
2           872       2.0                58          8.0
3           609       4.0               205         13.0
4          2560       2.0               189         10.0
5          1431       5.0               272         18.0
6           798       4.0                80         17.0
7          2986       5.0               177         10.0

**PREDICTING THE PRICE**


PRICE = M1 * AREA + M2 * NO. OF BEDROOMS + M3 * AGE + B

*PRICE BEING DEPENDED ON AREA ,NO 0F BEDROOMS AND AGE*

In [12]:
reg = linear_model.LinearRegression()
reg.fit(df[["Area (sq ft)","Bedrooms" ,"Age (years)"]] , df["Price (in lakhs)"])

LinearRegression()

In [13]:
reg.coef_

array([0.01583696, 4.73411379, 3.33661521])

In [14]:
reg.intercept_

68.66781863517704

Q - Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old

In [15]:
reg.predict([[3000 , 3 , 40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([263.84564069])

Q- Find price of home with 2500 sqr ft area, 4 bedrooms, 5 year old

In [16]:
reg.predict([[2500, 3 , 5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([139.14562968])

**Exercise**

In exercise folder (same level as this notebook on github) there is hiring.csv. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,

2 yr experience, 9 test score, 6 interview score

12 yr experience, 10 test score, 10 interview score

In [17]:
d = pd.read_csv("/kaggle/input/hiring/hiring.csv")
d["experience"] = d["experience"].fillna(0)
d["test_score(out of 10)"] = d["test_score(out of 10)"].fillna(math.floor(d["test_score(out of 10)"].mean()))

d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    7.0                           7      72000
7        11.0                    7.0                           8      80000

In [18]:
reg2 = linear_model.LinearRegression()
reg2.fit(d[["experience","test_score(out of 10)","interview_score(out of 10)"]],d["salary($)"])

LinearRegression()

In [19]:
reg2.predict([[2,9,6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [20]:
reg2.predict([[12,10,10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])